name: release

on: 
  push:
    tags: 
      - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-poetry
      steps:
        - uses: APN-Pucky/make-python-action@main
          with:
            test: true
            doc: false
            coveralls: true
            pypi-token: ${{ secrets.pypi_token }}
            gh-pages: false
